# Generated by script/render-homebrew-formula.sh in upwindsecurity/upwindctl.
# Do not edit by hand; the release workflow overwrites this file.
class Upwindctl < Formula
  desc "Command-line interface for Upwind Security services"
  homepage "https://upwind.io"
  version "0.40.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.40.0/upwindctl-v0.40.0-darwin-arm64"
      sha256 "92524da60825661aa7102ad931ce57e6a775f76152f929894b59119bfc59b1dd"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.40.0/upwindctl-v0.40.0-darwin-amd64"
      sha256 "c093dc09081f03300dda642935acd4b7fe864ae65b9bb173bf0964f96a4c34b6"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.40.0/upwindctl-v0.40.0-linux-arm64"
      sha256 "6d074ea2ce9a829e4e1cc83c3239783a5d94ffd64e1ee627700e73da4ae37970"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.40.0/upwindctl-v0.40.0-linux-amd64"
      sha256 "1fa55811b3b509edae4cdfbaaa304644ea5241d1fb092ec67465a73a0b5f3af2"
    end
  end

  def install
    # The release publishes bare binaries rather than archives, so the download
    # keeps its platform-suffixed name and arrives without the executable bit.
    bin.install Dir["upwindctl-*"].first => "upwindctl"
    chmod 0755, bin/"upwindctl"
    generate_completions_from_executable(bin/"upwindctl", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/upwindctl version")
  end
end
