# Generated by script/render-homebrew-formula.sh in upwindsecurity/upwindctl.
# Do not edit by hand; the release workflow overwrites this file.
class Upwindctl < Formula
  desc "Command-line interface for Upwind Security services"
  homepage "https://upwind.io"
  version "0.37.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.37.0/upwindctl-v0.37.0-darwin-arm64"
      sha256 "d1614b2988204c57bf5090693b6b90828ef69226d237aa9f0fb2e5dff4380333"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.37.0/upwindctl-v0.37.0-darwin-amd64"
      sha256 "ead89129e9bdf823aa538a8bce08de4e71561cf68d2c9673013783b5fe1481a3"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.37.0/upwindctl-v0.37.0-linux-arm64"
      sha256 "2360fc10b07a1106079137e7f73d051779eabe6c62d5bce668578419d392139c"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.37.0/upwindctl-v0.37.0-linux-amd64"
      sha256 "2e958fb2785d1bf7ccc85349f93c5c0cd1cce2c9379798626850629873a9080a"
    end
  end

  def install
    # The release publishes bare binaries rather than archives, so the download
    # keeps its platform-suffixed name and arrives without the executable bit.
    bin.install Dir["upwindctl-*"].first => "upwindctl"
    chmod 0755, bin/"upwindctl"
    generate_completions_from_executable(bin/"upwindctl", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/upwindctl version")
  end
end
