# Generated by script/render-homebrew-formula.sh in upwindsecurity/upwindctl.
# Do not edit by hand; the release workflow overwrites this file.
class Upwindctl < Formula
  desc "Command-line interface for Upwind Security services"
  homepage "https://upwind.io"
  version "0.39.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.39.0/upwindctl-v0.39.0-darwin-arm64"
      sha256 "473a37459c9daa0a411ac318cb0304a592df81110effe968070e309e606aa890"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.39.0/upwindctl-v0.39.0-darwin-amd64"
      sha256 "9378046bcc321d18d6eaef0058ea86339d800999de7a0181bb9b1aa4787aa8ba"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.upwind.io/upwindctl/v0.39.0/upwindctl-v0.39.0-linux-arm64"
      sha256 "22d7eb96d328233d7072343a92f34f0850d69ab8f6fc8769e75cc543a8ae8114"
    end
    on_intel do
      url "https://releases.upwind.io/upwindctl/v0.39.0/upwindctl-v0.39.0-linux-amd64"
      sha256 "091e8fa78cfedac1875a21ede35527c44cec361e2bd9a3fdb00ca659f12a51b6"
    end
  end

  def install
    # The release publishes bare binaries rather than archives, so the download
    # keeps its platform-suffixed name and arrives without the executable bit.
    bin.install Dir["upwindctl-*"].first => "upwindctl"
    chmod 0755, bin/"upwindctl"
    generate_completions_from_executable(bin/"upwindctl", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/upwindctl version")
  end
end
